import type { NamingStyleId, PersonalityId, ThemeId } from "@/lib/types"

// The FunCoin Universe: curated example brands. No prices, caps, volume or holders —
// on purpose. "trending" is an editorial order, not a market signal.

export type DiscoverTag =
  | "cute" | "chaotic" | "animals" | "ai" | "food" | "space" | "desi" | "internet" | "luxury" | "wholesome"
  | "office" | "gaming" | "sports" | "music" | "fantasy" | "weather"

export type DiscoverProject = {
  slug: string
  name: string
  ticker: string
  domain: string
  /** Generated coin artwork (public/coins). */
  coin: string
  /** Library mascot (public/mascots). */
  mascot: string
  personality: string[]
  tags: DiscoverTag[]
  description: string
  headline: string
  colors: [string, string, string, string]
  addedAt: string
  editorsPick: number
  remix: { topic: string; theme: ThemeId; personality: PersonalityId; namingStyle: NamingStyleId }
}

export const DISCOVER_PROJECTS: DiscoverProject[] = [
  {
    slug: "sleepy",
    name: "Sleepy",
    ticker: "SLEEPY",
    domain: "sleepy.fun",
    coin: "/coins/sleepy.webp",
    mascot: "/mascots/cat.webp",
    personality: ["Lazy", "Cute", "Chaotic"],
    tags: ["cute", "animals"],
    description: "The internet's laziest cat. Naps professionally, memes recreationally.",
    headline: "Too tired to be serious.",
    colors: ["#C9A7FF", "#8FD3FF", "#FFE38F", "#14101F"],
    addedAt: "2026-09-28",
    editorsPick: 1,
    remix: { topic: "Sleepy Cat", theme: "animals", personality: "cute", namingStyle: "short" },
  },
  {
    slug: "banana",
    name: "Banana Boss",
    ticker: "BANANA",
    domain: "banana.fun",
    coin: "/coins/banana.webp",
    mascot: "/mascots/banana.webp",
    personality: ["Funny", "Bossy", "Slippery"],
    tags: ["food", "chaotic"],
    description: "A banana in a tiny suit who runs every meeting and approves nothing.",
    headline: "Peel the vibes.",
    colors: ["#FFD60A", "#FF4D4D", "#3DB2FF", "#111018"],
    addedAt: "2026-09-26",
    editorsPick: 3,
    remix: { topic: "Banana Boss", theme: "food", personality: "funny", namingStyle: "character" },
  },
  {
    slug: "alien",
    name: "Alien Bro",
    ticker: "ALIEN",
    domain: "alien.fun",
    coin: "/coins/alien.webp",
    mascot: "/mascots/alien.webp",
    personality: ["Weird", "Friendly", "Lost"],
    tags: ["space", "internet"],
    description: "Came to Earth for research. Stayed for the memes and the free Wi-Fi.",
    headline: "Take me to your group chat.",
    colors: ["#7CFC8A", "#7B3FE4", "#E5E5E5", "#0D0B1A"],
    addedAt: "2026-09-24",
    editorsPick: 2,
    remix: { topic: "Alien", theme: "space", personality: "weird", namingStyle: "slang" },
  },
  {
    slug: "chad",
    name: "Chai Chad",
    ticker: "CHAD",
    domain: "chad.fun",
    coin: "/coins/chad.webp",
    mascot: "/mascots/chai.webp",
    personality: ["Confident", "Desi", "Warm"],
    tags: ["desi", "food"],
    description: "Brews chai at 4 PM sharp. Refuses to discuss coffee. Ever.",
    headline: "Chai first. Everything else later.",
    colors: ["#FFB86B", "#C2410C", "#FDE68A", "#1A1410"],
    addedAt: "2026-09-29",
    editorsPick: 4,
    remix: { topic: "Chai", theme: "indian", personality: "genz", namingStyle: "slang" },
  },
  {
    slug: "moondog",
    name: "Moondog",
    ticker: "MOONDOG",
    domain: "moondog.fun",
    coin: "/coins/moondog.webp",
    mascot: "/mascots/dog.webp",
    personality: ["Dreamy", "Loyal", "Goofy"],
    tags: ["animals", "space", "cute"],
    description: "A good boy who howls at the moon because he thinks it's a giant tennis ball.",
    headline: "Ball is life. Moon is ball.",
    colors: ["#8FD3FF", "#C9A7FF", "#FFF4E0", "#0B1020"],
    addedAt: "2026-09-20",
    editorsPick: 5,
    remix: { topic: "Moon Dog", theme: "animals", personality: "wholesome", namingStyle: "oneword" },
  },
  {
    slug: "sleepyai",
    name: "SleepyAI",
    ticker: "SLPYAI",
    domain: "sleepyai.fun",
    coin: "/coins/sleepyai.webp",
    mascot: "/mascots/robot.webp",
    personality: ["Sleepy", "Smart", "Glitchy"],
    tags: ["ai", "cute"],
    description: "An AI that answers every question with a yawn and a surprisingly good haiku.",
    headline: "Processing… please wait 8 hours.",
    colors: ["#2EC5FF", "#C9D1E0", "#FF4FD8", "#0A0A0A"],
    addedAt: "2026-09-30",
    editorsPick: 6,
    remix: { topic: "Sleepy AI Robot", theme: "ai", personality: "absurd", namingStyle: "internet" },
  },
  {
    slug: "frogking",
    name: "Frog King",
    ticker: "FROGK",
    domain: "frogking.fun",
    coin: "/coins/frogking.webp",
    mascot: "/mascots/frog.webp",
    personality: ["Royal", "Dramatic", "Damp"],
    tags: ["animals", "luxury"],
    description: "Rules a single lily pad with an iron webbed fist and a velvet cape.",
    headline: "Kneel before the pond.",
    colors: ["#F5C451", "#10B981", "#6D28D9", "#0B0A0F"],
    addedAt: "2026-09-18",
    editorsPick: 8,
    remix: { topic: "Frog King", theme: "animals", personality: "luxury", namingStyle: "character" },
  },
  {
    slug: "gooseglitch",
    name: "goose.exe",
    ticker: "GOOSEEXE",
    domain: "gooseexe.fun",
    coin: "/coins/gooseglitch.webp",
    mascot: "/mascots/goose.webp",
    personality: ["Chaotic", "Loud", "Unstoppable"],
    tags: ["animals", "chaotic", "internet"],
    description: "A goose that escaped a video game and now honks at your browser tabs.",
    headline: "HONK has entered the chat.",
    colors: ["#B6FF2E", "#FF2E88", "#8B2EFF", "#0A0710"],
    addedAt: "2026-09-27",
    editorsPick: 7,
    remix: { topic: "Goose", theme: "internet", personality: "chaotic", namingStyle: "internet" },
  },
  {
    slug: "samosasquad",
    name: "Samosa Squad",
    ticker: "SAMOSA",
    domain: "samosasquad.fun",
    coin: "/coins/samosasquad.webp",
    mascot: "/mascots/samosa.webp",
    personality: ["Crunchy", "Wholesome", "Spicy"],
    tags: ["desi", "food", "wholesome"],
    description: "Three samosas who solve every problem with extra chutney and group hugs.",
    headline: "Crispy outside. Soft inside.",
    colors: ["#FFB627", "#7EE081", "#FF5EAE", "#1A1208"],
    addedAt: "2026-09-22",
    editorsPick: 9,
    remix: { topic: "Samosa", theme: "desi", personality: "wholesome", namingStyle: "slang" },
  },
  {
    slug: "capybro",
    name: "Capybro",
    ticker: "CAPY",
    domain: "capybro.fun",
    coin: "/coins/capybro.webp",
    mascot: "/mascots/capybara.webp",
    personality: ["Chill", "Unbothered", "Kind"],
    tags: ["animals", "wholesome", "cute"],
    description: "Sits in hot springs. Befriends everyone. Has never once been stressed.",
    headline: "Okay I pull up.",
    colors: ["#FFB38A", "#9BF6D0", "#FF6FB5", "#2A1A1F"],
    addedAt: "2026-09-15",
    editorsPick: 10,
    remix: { topic: "Capybara", theme: "animals", personality: "wholesome", namingStyle: "slang" },
  },
  {
    slug: "pizzalord",
    name: "Lord Pizzington",
    ticker: "PIZZA",
    domain: "pizzington.fun",
    coin: "/coins/pizzalord.webp",
    mascot: "/mascots/pizza.webp",
    personality: ["Luxury", "Cheesy", "Extra"],
    tags: ["food", "luxury"],
    description: "A pizza slice with a monocle who only attends galas that serve ranch.",
    headline: "Extra cheese is a lifestyle.",
    colors: ["#F5C451", "#FF4D4D", "#F3E3C3", "#130B07"],
    addedAt: "2026-09-12",
    editorsPick: 12,
    remix: { topic: "Pizza", theme: "food", personality: "luxury", namingStyle: "character" },
  },
  {
    slug: "npcgpt",
    name: "NpcGPT",
    ticker: "NPCGPT",
    domain: "npcgpt.fun",
    coin: "/coins/npcgpt.webp",
    mascot: "/mascots/npc.webp",
    personality: ["Repetitive", "Absurd", "Polite"],
    tags: ["ai", "internet", "chaotic"],
    description: "An AI that only knows three lines of dialogue and uses them with confidence.",
    headline: "Nice weather we're having.",
    colors: ["#2EF2D0", "#FFB627", "#5B2EFF", "#0D0B1A"],
    addedAt: "2026-09-25",
    editorsPick: 11,
    remix: { topic: "NPC", theme: "ai", personality: "absurd", namingStyle: "internet" },
  },
  {
    slug: "captaintoast",
    name: "Captain Toast",
    ticker: "TOAST",
    domain: "captaintoast.fun",
    coin: "/coins/captaintoast.webp",
    mascot: "/mascots/waffle.webp",
    personality: ["Heroic", "Crispy", "Earnest"],
    tags: ["food", "wholesome"],
    description: "A slice of toast in a red cape who rescues breakfasts before they go cold.",
    headline: "Butter days are coming.",
    colors: ["#FFC86B", "#E63946", "#FFF1D6", "#1A120A"],
    addedAt: "2026-10-09",
    editorsPick: 13,
    remix: { topic: "Captain Toast", theme: "food", personality: "funny", namingStyle: "character" },
  },
  {
    slug: "mothlamp",
    name: "Moth Lamp",
    ticker: "MOTHLAMP",
    domain: "mothlamp.fun",
    coin: "/coins/mothlamp.webp",
    mascot: "/mascots/bird.webp",
    personality: ["Devoted", "Dreamy", "Fluttery"],
    tags: ["animals", "cute", "office"],
    description: "A fuzzy moth hopelessly in love with a desk lamp. Writes it poems every single night.",
    headline: "It's not a crush. It's a calling.",
    colors: ["#FFE38F", "#B8A1FF", "#F5EBDD", "#14111C"],
    addedAt: "2026-10-08",
    editorsPick: 14,
    remix: { topic: "Moth Lamp", theme: "animals", personality: "weird", namingStyle: "phrase" },
  },
  {
    slug: "chaiwalacat",
    name: "Chai Wala Cat",
    ticker: "CHAICAT",
    domain: "chaiwalacat.fun",
    coin: "/coins/chaiwalacat.webp",
    mascot: "/mascots/cat.webp",
    personality: ["Warm", "Focused", "Cozy"],
    tags: ["desi", "food", "animals"],
    description: "A cat who brews masala chai with full concentration and judges anyone who asks for sugar-free.",
    headline: "Kadak chai. Softer paws.",
    colors: ["#E8A15C", "#8B3A1F", "#FFE9C7", "#1A100B"],
    addedAt: "2026-10-07",
    editorsPick: 15,
    remix: { topic: "Chai Wala Cat", theme: "indian", personality: "cute", namingStyle: "slang" },
  },
  {
    slug: "noodleninja",
    name: "Noodle Ninja",
    ticker: "NOODLE",
    domain: "noodleninja.fun",
    coin: "/coins/noodleninja.webp",
    mascot: "/mascots/ramen.webp",
    personality: ["Swift", "Slurpy", "Stealthy"],
    tags: ["food", "chaotic"],
    description: "A ramen bowl in a ninja headband. Strikes fast, slurps faster, never spills.",
    headline: "Silent but slurpy.",
    colors: ["#FF5A3C", "#FFD166", "#2B2D42", "#0C0B10"],
    addedAt: "2026-10-06",
    editorsPick: 16,
    remix: { topic: "Noodle Ninja", theme: "food", personality: "aggressive", namingStyle: "character" },
  },
  {
    slug: "penguinpayroll",
    name: "Penguin Payroll",
    ticker: "PAYROLL",
    domain: "penguinpayroll.fun",
    coin: "/coins/penguinpayroll.webp",
    mascot: "/mascots/penguin.webp",
    personality: ["Diligent", "Formal", "Overworked"],
    tags: ["office", "animals"],
    description: "A penguin in a tiny tie who staples every form twice and alphabetizes the snacks.",
    headline: "Please see attached.",
    colors: ["#7FB7FF", "#F2F2F2", "#FFB703", "#0D1220"],
    addedAt: "2026-10-05",
    editorsPick: 17,
    remix: { topic: "Penguin Payroll", theme: "culture", personality: "funny", namingStyle: "brand" },
  },
  {
    slug: "cloudnap",
    name: "Cloud Nap",
    ticker: "CLOUDNAP",
    domain: "cloudnap.fun",
    coin: "/coins/cloudnap.webp",
    mascot: "/mascots/cloud.webp",
    personality: ["Sleepy", "Soft", "Drizzly"],
    tags: ["weather", "cute"],
    description: "A sleepy rain cloud that drizzles a little whenever it dreams.",
    headline: "Forecast: 100% nap.",
    colors: ["#A9C8FF", "#E4D9FF", "#FFFFFF", "#101528"],
    addedAt: "2026-10-04",
    editorsPick: 18,
    remix: { topic: "Cloud Nap", theme: "random", personality: "cute", namingStyle: "oneword" },
  },
  {
    slug: "retrorobo",
    name: "Retro Robo",
    ticker: "RETRO",
    domain: "retrorobo.fun",
    coin: "/coins/retrorobo.webp",
    mascot: "/mascots/robot.webp",
    personality: ["Groovy", "Nostalgic", "Clunky"],
    tags: ["ai", "music"],
    description: "An 80s robot with a cassette player for a chest. Only plays one mixtape, on repeat.",
    headline: "Rewind. Replay. Robot.",
    colors: ["#FF6EC7", "#2EC5FF", "#FFD23F", "#0E0A1A"],
    addedAt: "2026-10-03",
    editorsPick: 19,
    remix: { topic: "Retro Robot", theme: "ai", personality: "funny", namingStyle: "internet" },
  },
  {
    slug: "tacoturtle",
    name: "Taco Tuesday Turtle",
    ticker: "TACOTURT",
    domain: "tacoturtle.fun",
    coin: "/coins/tacoturtle.webp",
    mascot: "/mascots/taco.webp",
    personality: ["Slow", "Snacky", "Content"],
    tags: ["food", "animals", "wholesome"],
    description: "A turtle who wears a taco shell and arrives at every party exactly one day late.",
    headline: "Slow food, literally.",
    colors: ["#FFC145", "#6BBF59", "#E94F37", "#1A1508"],
    addedAt: "2026-10-02",
    editorsPick: 20,
    remix: { topic: "Taco Turtle", theme: "food", personality: "wholesome", namingStyle: "phrase" },
  },
  {
    slug: "laserllama",
    name: "Laser Llama",
    ticker: "LLAMA",
    domain: "laserllama.fun",
    coin: "/coins/laserllama.webp",
    mascot: "/mascots/unicorn.webp",
    personality: ["Dramatic", "Fluffy", "Intense"],
    tags: ["animals", "chaotic"],
    description: "A fluffy llama in laser goggles who stares down every problem until it goes away.",
    headline: "Eyes on the prize. Lasers on.",
    colors: ["#FF2E63", "#08D9D6", "#F4E9D8", "#0B0B14"],
    addedAt: "2026-10-01",
    editorsPick: 21,
    remix: { topic: "Laser Llama", theme: "animals", personality: "chaotic", namingStyle: "short" },
  },
  {
    slug: "discoduck",
    name: "Disco Duck",
    ticker: "DISCO",
    domain: "discoduck.fun",
    coin: "/coins/discoduck.webp",
    mascot: "/mascots/duck.webp",
    personality: ["Groovy", "Shiny", "Extra"],
    tags: ["music", "animals"],
    description: "A duck who carries a mirrorball everywhere, just in case a dance floor breaks out.",
    headline: "Quack to the beat.",
    colors: ["#FFD60A", "#C77DFF", "#4CC9F0", "#120A1F"],
    addedAt: "2026-09-30",
    editorsPick: 22,
    remix: { topic: "Disco Duck", theme: "animals", personality: "funny", namingStyle: "slang" },
  },
  {
    slug: "wizardfrog",
    name: "Wizard Frog",
    ticker: "WIZFROG",
    domain: "wizardfrog.fun",
    coin: "/coins/wizardfrog.webp",
    mascot: "/mascots/wizard.webp",
    personality: ["Mystic", "Croaky", "Wise"],
    tags: ["fantasy", "animals"],
    description: "A frog in a starry wizard hat who casts spells mostly to summon more flies.",
    headline: "Ribbit, but make it magic.",
    colors: ["#7B5CFF", "#39D98A", "#FFE066", "#0B0A1E"],
    addedAt: "2026-09-29",
    editorsPick: 23,
    remix: { topic: "Wizard Frog", theme: "animals", personality: "weird", namingStyle: "character" },
  },
  {
    slug: "bobabunny",
    name: "Bubble Tea Bunny",
    ticker: "BOBABUN",
    domain: "bobabunny.fun",
    coin: "/coins/bobabunny.webp",
    mascot: "/mascots/hamster.webp",
    personality: ["Bouncy", "Sweet", "Chewy"],
    tags: ["cute", "food"],
    description: "A bunny who lives in a boba cup and insists the pearls are its emotional support friends.",
    headline: "Chewy thoughts only.",
    colors: ["#F7C6D9", "#C8A27A", "#FFF4E6", "#1E1418"],
    addedAt: "2026-10-09",
    editorsPick: 24,
    remix: { topic: "Bubble Tea Bunny", theme: "food", personality: "cute", namingStyle: "oneword" },
  },
  {
    slug: "grumpycactus",
    name: "Grumpy Cactus",
    ticker: "CACTUS",
    domain: "grumpycactus.fun",
    coin: "/coins/grumpycactus.webp",
    mascot: "/mascots/pickle.webp",
    personality: ["Prickly", "Fancy", "Unimpressed"],
    tags: ["luxury", "chaotic"],
    description: "A cactus with a monocle who finds everything a bit beneath him, especially hugs.",
    headline: "Do not touch. Thank you.",
    colors: ["#4CAF50", "#F5C451", "#F28AB2", "#0E140C"],
    addedAt: "2026-10-08",
    editorsPick: 25,
    remix: { topic: "Grumpy Cactus", theme: "random", personality: "luxury", namingStyle: "character" },
  },
  {
    slug: "spacehamster",
    name: "Space Hamster",
    ticker: "HAMSTR",
    domain: "spacehamster.fun",
    coin: "/coins/spacehamster.webp",
    mascot: "/mascots/hamster.webp",
    personality: ["Brave", "Tiny", "Curious"],
    tags: ["space", "animals", "cute"],
    description: "A hamster in a fishbowl helmet exploring the galaxy one sunflower seed at a time.",
    headline: "One small step for paws.",
    colors: ["#FFB570", "#5B8CFF", "#F2F5FF", "#0A0E22"],
    addedAt: "2026-10-07",
    editorsPick: 26,
    remix: { topic: "Space Hamster", theme: "space", personality: "cute", namingStyle: "short" },
  },
  {
    slug: "vadapavviking",
    name: "Vada Pav Viking",
    ticker: "VADAPAV",
    domain: "vadapavviking.fun",
    coin: "/coins/vadapavviking.webp",
    mascot: "/mascots/burger.webp",
    personality: ["Bold", "Spicy", "Loud"],
    tags: ["desi", "food"],
    description: "A vada pav in a horned helmet who conquers every street corner with green chutney.",
    headline: "Raid the tapri.",
    colors: ["#F4A259", "#5B8E7D", "#BC4B51", "#1A1109"],
    addedAt: "2026-10-06",
    editorsPick: 27,
    remix: { topic: "Vada Pav Viking", theme: "desi", personality: "aggressive", namingStyle: "slang" },
  },
  {
    slug: "lofiowl",
    name: "Lofi Owl",
    ticker: "LOFI",
    domain: "lofiowl.fun",
    coin: "/coins/lofiowl.webp",
    mascot: "/mascots/owl.webp",
    personality: ["Calm", "Studious", "Mellow"],
    tags: ["music", "animals"],
    description: "An owl in big headphones studying by a rainy window. Has never once finished the playlist.",
    headline: "Beats to hoot to.",
    colors: ["#8E7DBE", "#F2C14E", "#A3C4F3", "#121022"],
    addedAt: "2026-10-05",
    editorsPick: 28,
    remix: { topic: "Lofi Owl", theme: "animals", personality: "wholesome", namingStyle: "internet" },
  },
  {
    slug: "gymgoat",
    name: "Gym Goat",
    ticker: "GYMGOAT",
    domain: "gymgoat.fun",
    coin: "/coins/gymgoat.webp",
    mascot: "/mascots/gym.webp",
    personality: ["Determined", "Sweaty", "Proud"],
    tags: ["sports", "animals"],
    description: "A goat who lifts tiny dumbbells with total commitment and never skips leg day.",
    headline: "Hooves up. Reps in.",
    colors: ["#FF6B35", "#F7F7F2", "#3A86FF", "#0F0F14"],
    addedAt: "2026-10-04",
    editorsPick: 29,
    remix: { topic: "Gym Goat", theme: "animals", personality: "aggressive", namingStyle: "slang" },
  },
  {
    slug: "pandapixel",
    name: "Panda Pixel",
    ticker: "PIXEL",
    domain: "pandapixel.fun",
    coin: "/coins/pandapixel.webp",
    mascot: "/mascots/panda.webp",
    personality: ["Blocky", "Cute", "Retro"],
    tags: ["gaming", "animals", "cute"],
    description: "An 8-bit panda who respawns after every nap with full bamboo restored.",
    headline: "Press start to snack.",
    colors: ["#F2F2F2", "#3DDC97", "#FF5D8F", "#0A0A0F"],
    addedAt: "2026-10-03",
    editorsPick: 30,
    remix: { topic: "Pixel Panda", theme: "gaming", personality: "cute", namingStyle: "internet" },
  },
  {
    slug: "mememonk",
    name: "Meme Monk",
    ticker: "MONK",
    domain: "mememonk.fun",
    coin: "/coins/mememonk.webp",
    mascot: "/mascots/npc.webp",
    personality: ["Calm", "Wise", "Online"],
    tags: ["internet", "wholesome"],
    description: "A peaceful monk who meditates while scrolling, and somehow still finds inner calm.",
    headline: "Breathe in. Scroll out.",
    colors: ["#F4A261", "#E9C46A", "#2A9D8F", "#14110D"],
    addedAt: "2026-10-02",
    editorsPick: 31,
    remix: { topic: "Meme Monk", theme: "internet", personality: "wholesome", namingStyle: "phrase" },
  },
  {
    slug: "sushisumo",
    name: "Sushi Sumo",
    ticker: "SUMO",
    domain: "sushisumo.fun",
    coin: "/coins/sushisumo.webp",
    mascot: "/mascots/burrito.webp",
    personality: ["Mighty", "Round", "Polite"],
    tags: ["food", "sports"],
    description: "A sushi roll sumo wrestler who bows before every match and wins by being adorable.",
    headline: "Roll in. Stand firm.",
    colors: ["#FF8C61", "#F7F3E9", "#2D6A4F", "#0E120F"],
    addedAt: "2026-10-01",
    editorsPick: 32,
    remix: { topic: "Sushi Sumo", theme: "food", personality: "aggressive", namingStyle: "character" },
  },
  {
    slug: "couchpotatoking",
    name: "Couch Potato King",
    ticker: "COUCHKING",
    domain: "couchpotatoking.fun",
    coin: "/coins/couchpotatoking.webp",
    mascot: "/mascots/potato.webp",
    personality: ["Royal", "Relaxed", "Snacky"],
    tags: ["food", "luxury"],
    description: "A potato on a sofa throne who rules the kingdom from the remote control.",
    headline: "Long live the lounge.",
    colors: ["#C9A227", "#8B5E3C", "#7B2CBF", "#140E08"],
    addedAt: "2026-09-30",
    editorsPick: 33,
    remix: { topic: "Couch Potato King", theme: "food", personality: "luxury", namingStyle: "character" },
  },
  {
    slug: "krakenkeyboard",
    name: "Kraken Keyboard",
    ticker: "KRAKEN",
    domain: "krakenkeyboard.fun",
    coin: "/coins/krakenkeyboard.webp",
    mascot: "/mascots/shark.webp",
    personality: ["Busy", "Clever", "Clacky"],
    tags: ["office", "chaotic"],
    description: "An octopus typing on four keyboards at once and replying to every email in under a second.",
    headline: "Eight arms. Zero inbox.",
    colors: ["#9D4EDD", "#00F5D4", "#FF9E00", "#0B0820"],
    addedAt: "2026-09-29",
    editorsPick: 34,
    remix: { topic: "Kraken Keyboard", theme: "internet", personality: "chaotic", namingStyle: "brand" },
  },
  {
    slug: "rocketsnail",
    name: "Rocket Snail",
    ticker: "SNAIL",
    domain: "rocketsnail.fun",
    coin: "/coins/rocketsnail.webp",
    mascot: "/mascots/rocket.webp",
    personality: ["Patient", "Bold", "Zoomy"],
    tags: ["space", "animals"],
    description: "A snail who strapped on a jetpack and now arrives at exactly the same speed, but louder.",
    headline: "Slow and steady, now with thrusters.",
    colors: ["#FF7B54", "#FFD56F", "#6C5CE7", "#120E1C"],
    addedAt: "2026-10-09",
    editorsPick: 35,
    remix: { topic: "Rocket Snail", theme: "space", personality: "funny", namingStyle: "phrase" },
  },
  {
    slug: "biryanibear",
    name: "Biryani Bear",
    ticker: "BIRYBEAR",
    domain: "biryanibear.fun",
    coin: "/coins/biryanibear.webp",
    mascot: "/mascots/bear.webp",
    personality: ["Protective", "Hungry", "Warm"],
    tags: ["desi", "food", "animals"],
    description: "A bear who guards the biryani pot at every family function. Nobody gets the potato first.",
    headline: "The handi is under protection.",
    colors: ["#E9A23B", "#7A4E2D", "#4CAF50", "#1A1008"],
    addedAt: "2026-10-08",
    editorsPick: 36,
    remix: { topic: "Biryani Bear", theme: "desi", personality: "wholesome", namingStyle: "slang" },
  },
  {
    slug: "glitchghost",
    name: "Glitch Ghost",
    ticker: "GLITCH",
    domain: "glitchghost.fun",
    coin: "/coins/glitchghost.webp",
    mascot: "/mascots/ghost.webp",
    personality: ["Spooky", "Buggy", "Shy"],
    tags: ["gaming", "internet"],
    description: "A pixel ghost made of scanlines who haunts old save files and apologizes for the lag.",
    headline: "Boo. Buffering.",
    colors: ["#00F0FF", "#FF00A8", "#E6E6FA", "#07070D"],
    addedAt: "2026-10-07",
    editorsPick: 37,
    remix: { topic: "Glitch Ghost", theme: "gaming", personality: "weird", namingStyle: "internet" },
  },
  {
    slug: "sneakershark",
    name: "Sneaker Shark",
    ticker: "SNEAKSHARK",
    domain: "sneakershark.fun",
    coin: "/coins/sneakershark.webp",
    mascot: "/mascots/shark.webp",
    personality: ["Fresh", "Fast", "Stylish"],
    tags: ["sports", "animals"],
    description: "A shark in high-top sneakers who keeps them spotless, even underwater.",
    headline: "Fresh fins. Fresher kicks.",
    colors: ["#3A86FF", "#FFBE0B", "#FB5607", "#0A0F1E"],
    addedAt: "2026-10-06",
    editorsPick: 38,
    remix: { topic: "Sneaker Shark", theme: "animals", personality: "genz", namingStyle: "slang" },
  },
  {
    slug: "dragondumpling",
    name: "Dragon Dumpling",
    ticker: "DRAGDUMP",
    domain: "dragondumpling.fun",
    coin: "/coins/dragondumpling.webp",
    mascot: "/mascots/dragon.webp",
    personality: ["Tiny", "Fiery", "Adorable"],
    tags: ["fantasy", "food", "cute"],
    description: "A baby dragon hatching from a steamed dumpling, already asking for chilli oil.",
    headline: "Born steamy.",
    colors: ["#FF6F59", "#7BD389", "#FFF3E2", "#170D0C"],
    addedAt: "2026-10-05",
    editorsPick: 39,
    remix: { topic: "Dragon Dumpling", theme: "food", personality: "cute", namingStyle: "character" },
  },
  {
    slug: "cricketcrow",
    name: "Cricket Crow",
    ticker: "CROW",
    domain: "cricketcrow.fun",
    coin: "/coins/cricketcrow.webp",
    mascot: "/mascots/cricket.webp",
    personality: ["Sharp", "Cheeky", "Sporty"],
    tags: ["sports", "desi", "animals"],
    description: "A crow with a cricket bat who has never lost a gully match, mostly by changing the rules.",
    headline: "Gully rules apply.",
    colors: ["#2B2D42", "#8ECAE6", "#FFB703", "#0B0B10"],
    addedAt: "2026-10-04",
    editorsPick: 40,
    remix: { topic: "Cricket Crow", theme: "indian", personality: "funny", namingStyle: "slang" },
  },
  {
    slug: "weatherdog",
    name: "Weather Wizard Dog",
    ticker: "FORECAST",
    domain: "weatherdog.fun",
    coin: "/coins/weatherdog.webp",
    mascot: "/mascots/dog.webp",
    personality: ["Wise", "Loyal", "Breezy"],
    tags: ["weather", "fantasy", "animals"],
    description: "A dog with a wizard staff who forecasts the weather by sniffing the wind. Usually right.",
    headline: "Sunny with a chance of zoomies.",
    colors: ["#5DADE2", "#F7DC6F", "#A569BD", "#0D1324"],
    addedAt: "2026-10-03",
    editorsPick: 41,
    remix: { topic: "Weather Wizard Dog", theme: "animals", personality: "wholesome", namingStyle: "character" },
  },
  {
    slug: "jellyjetpack",
    name: "Jelly Jetpack",
    ticker: "JELLY",
    domain: "jellyjetpack.fun",
    coin: "/coins/jellyjetpack.webp",
    mascot: "/mascots/astronaut.webp",
    personality: ["Floaty", "Gentle", "Glowy"],
    tags: ["space", "cute"],
    description: "A jellyfish astronaut who drifts between planets and glows a little when happy.",
    headline: "Float on.",
    colors: ["#FF8FD8", "#7DF9FF", "#C3B1E1", "#0A0820"],
    addedAt: "2026-10-02",
    editorsPick: 42,
    remix: { topic: "Jelly Astronaut", theme: "space", personality: "weird", namingStyle: "oneword" },
  },
  {
    slug: "midnightfridge",
    name: "Midnight Fridge",
    ticker: "FRIDGE",
    domain: "midnightfridge.fun",
    coin: "/coins/midnightfridge.webp",
    mascot: "/mascots/cheese.webp",
    personality: ["Mysterious", "Generous", "Humming"],
    tags: ["food", "chaotic"],
    description: "A glowing fridge with eyes that opens itself at 2 AM and whispers about leftovers.",
    headline: "Just one more snack.",
    colors: ["#BDE0FE", "#FFD166", "#CDB4DB", "#0B0D18"],
    addedAt: "2026-10-01",
    editorsPick: 43,
    remix: { topic: "Midnight Fridge", theme: "food", personality: "chaotic", namingStyle: "phrase" },
  },
  {
    slug: "apearchitect",
    name: "Ape Architect",
    ticker: "APEARCH",
    domain: "apearchitect.fun",
    coin: "/coins/apearchitect.webp",
    mascot: "/mascots/monkey.webp",
    personality: ["Clever", "Busy", "Ambitious"],
    tags: ["office", "animals"],
    description: "An ape in a hard hat with blueprints for a treehouse that keeps getting more floors.",
    headline: "Measure twice. Swing once.",
    colors: ["#FFB703", "#219EBC", "#8D6E63", "#0F1216"],
    addedAt: "2026-09-30",
    editorsPick: 44,
    remix: { topic: "Ape Architect", theme: "animals", personality: "funny", namingStyle: "brand" },
  },
  {
    slug: "bananaphone",
    name: "Banana Phone",
    ticker: "BANAPHONE",
    domain: "bananaphone.fun",
    coin: "/coins/bananaphone.webp",
    mascot: "/mascots/banana.webp",
    personality: ["Chatty", "Retro", "Silly"],
    tags: ["food", "internet"],
    description: "A banana who answers a retro rotary phone and talks for hours about absolutely nothing.",
    headline: "Ring ring. It's for you.",
    colors: ["#FFE14D", "#FF6392", "#5AA9E6", "#15120A"],
    addedAt: "2026-09-29",
    editorsPick: 45,
    remix: { topic: "Banana Phone", theme: "food", personality: "absurd", namingStyle: "phrase" },
  },
  {
    slug: "cybersamuraicat",
    name: "Cyber Samurai Cat",
    ticker: "CYBERCAT",
    domain: "cybersamuraicat.fun",
    coin: "/coins/cybersamuraicat.webp",
    mascot: "/mascots/ninja.webp",
    personality: ["Honorable", "Sleek", "Electric"],
    tags: ["gaming", "animals", "ai"],
    description: "A cat in neon samurai armor who guards the server room and naps on the warm racks.",
    headline: "Honor. Purr. Repeat.",
    colors: ["#FF2079", "#00F0FF", "#B026FF", "#06050D"],
    addedAt: "2026-10-09",
    editorsPick: 46,
    remix: { topic: "Cyber Samurai Cat", theme: "gaming", personality: "aggressive", namingStyle: "character" },
  },
  {
    slug: "parrotdj",
    name: "Pirate Parrot DJ",
    ticker: "PARROTDJ",
    domain: "parrotdj.fun",
    coin: "/coins/parrotdj.webp",
    mascot: "/mascots/pirate.webp",
    personality: ["Loud", "Rhythmic", "Swashbuckling"],
    tags: ["music", "animals", "chaotic"],
    description: "A parrot with an eye patch who spins sea shanty remixes and repeats the drop on request.",
    headline: "Drop the anchor. Drop the beat.",
    colors: ["#2ECC71", "#E74C3C", "#F1C40F", "#0D0F12"],
    addedAt: "2026-10-08",
    editorsPick: 47,
    remix: { topic: "Pirate Parrot DJ", theme: "animals", personality: "chaotic", namingStyle: "slang" },
  },
  {
    slug: "moonmochi",
    name: "Moon Mochi",
    ticker: "MOCHI",
    domain: "moonmochi.fun",
    coin: "/coins/moonmochi.webp",
    mascot: "/mascots/moon.webp",
    personality: ["Soft", "Dreamy", "Squishy"],
    tags: ["space", "cute", "food"],
    description: "A round mochi floating through space, quietly wondering if the moon is its cousin.",
    headline: "Squish among the stars.",
    colors: ["#FFD1DC", "#B5EAD7", "#FFF5E1", "#0E0B1E"],
    addedAt: "2026-10-07",
    editorsPick: 48,
    remix: { topic: "Moon Mochi", theme: "space", personality: "cute", namingStyle: "oneword" },
  },
]

export const DISCOVER_FILTERS = [
  { id: "newest", label: "Newest" },
  { id: "trending", label: "Trending" },
  { id: "random", label: "Random" },
  { id: "cute", label: "Cute" },
  { id: "chaotic", label: "Chaotic" },
  { id: "animals", label: "Animals" },
  { id: "ai", label: "AI" },
  { id: "food", label: "Food" },
  { id: "office", label: "Office" },
  { id: "gaming", label: "Gaming" },
  { id: "sports", label: "Sports" },
  { id: "music", label: "Music" },
  { id: "fantasy", label: "Fantasy" },
  { id: "weather", label: "Weather" },
] as const
export type DiscoverFilter = (typeof DISCOVER_FILTERS)[number]["id"]

export function remixHref(p: DiscoverProject) {
  const q = new URLSearchParams({ topic: p.remix.topic, theme: p.remix.theme, personality: p.remix.personality, style: p.remix.namingStyle })
  return `/create?${q.toString()}`
}

export const HERO_EXAMPLES = [
  { ticker: "MOONDOG", domain: "moondog.fun", coin: "/coins/moondog.webp", line: "Howls at the moon. Thinks it's a tennis ball." },
  { ticker: "BANANABOSS", domain: "bananaboss.fun", coin: "/coins/banana.webp", line: "Runs every meeting. Approves nothing." },
  { ticker: "SLEEPYAI", domain: "sleepyai.fun", coin: "/coins/sleepyai.webp", line: "Answers in yawns and haikus." },
  { ticker: "CHAICHAD", domain: "chaichad.fun", coin: "/coins/chad.webp", line: "4 PM chai. Non-negotiable." },
  { ticker: "ALIENBRO", domain: "alienbro.fun", coin: "/coins/alien.webp", line: "Came for research. Stayed for memes." },
  { ticker: "TOAST", domain: "captaintoast.fun", coin: "/coins/captaintoast.webp", line: "Wears a cape. Saves breakfast." },
  { ticker: "DISCO", domain: "discoduck.fun", coin: "/coins/discoduck.webp", line: "Carries a mirrorball. Just in case." },
  { ticker: "CHAICAT", domain: "chaiwalacat.fun", coin: "/coins/chaiwalacat.webp", line: "Brews kadak chai. Judges sugar-free." },
  { ticker: "SNAIL", domain: "rocketsnail.fun", coin: "/coins/rocketsnail.webp", line: "Got a jetpack. Same speed, louder." },
  { ticker: "MOCHI", domain: "moonmochi.fun", coin: "/coins/moonmochi.webp", line: "Floats in space. Stays squishy." },
]
