/**
 * Owner details the legal pages need. All from env, all optional: where a value is blank the page
 * leaves that sentence or section out. Nothing here is ever invented or shown as a placeholder.
 *
 * These are decisions for the owner and their lawyer (who operates the site, which law applies,
 * where the service is not offered). The code only displays and enforces what they set.
 */

const env = (v: string | undefined) => (v ?? "").trim().replace(/^["']|["']$/g, "").trim()
const email = (v: string | undefined) => {
  const e = env(v)
  return /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(e) ? e : ""
}

const DEFAULT_MIN_AGE = 18
const minAge = (v: string | undefined) => {
  const n = Number.parseInt(env(v), 10)
  return Number.isInteger(n) && n >= 13 && n <= 25 ? n : DEFAULT_MIN_AGE
}

// NEXT_PUBLIC_ values are read by name so Next.js can inline them in the browser bundle too.
export const LEGAL = {
  /** The person or company that operates the site. */
  entity: env(process.env.NEXT_PUBLIC_LEGAL_ENTITY),
  address: env(process.env.NEXT_PUBLIC_LEGAL_ADDRESS),
  country: env(process.env.NEXT_PUBLIC_LEGAL_COUNTRY),
  governingLaw: env(process.env.NEXT_PUBLIC_GOVERNING_LAW),
  disputeVenue: env(process.env.NEXT_PUBLIC_DISPUTE_VENUE),
  privacyEmail: email(process.env.NEXT_PUBLIC_PRIVACY_EMAIL),
  copyrightEmail: email(process.env.NEXT_PUBLIC_COPYRIGHT_EMAIL),
  minAge: minAge(process.env.NEXT_PUBLIC_MIN_AGE),
}

/**
 * ISO 3166-1 alpha-2 country codes where the service is not offered, from the server-only
 * RESTRICTED_COUNTRIES (comma-separated). Empty by default and always empty in the browser.
 */
export function restrictedCountries(): string[] {
  return env(process.env.RESTRICTED_COUNTRIES)
    .split(",")
    .map((c) => c.trim().toUpperCase())
    .filter((c) => /^[A-Z]{2}$/.test(c))
}

export const isRestrictedCountry = (code: string | null | undefined) => Boolean(code) && restrictedCountries().includes(code!.trim().toUpperCase())

/**
 * Which outside services this deployment actually uses, so the legal pages name the real ones and
 * not a generic list. Server-side only (it reads server env); in the browser everything reads "off".
 */
export function legalProviders() {
  const has = (v: string | undefined) => Boolean(env(v))
  const textKey = has(process.env.AI_API_KEY)
  const textProvider = (env(process.env.AI_PROVIDER).toLowerCase() || (textKey ? "anthropic" : "local")) as string
  const imageOn = env(process.env.IMAGE_PROVIDER).toLowerCase() === "openai" && (has(process.env.IMAGE_API_KEY) || has(process.env.OPENAI_API_KEY) || textKey)
  const ai = new Set<string>()
  if (textKey && textProvider === "anthropic") ai.add("Anthropic")
  if (textKey && textProvider === "openai") ai.add("OpenAI")
  if (imageOn) ai.add("OpenAI")
  const rpc = env(process.env.SOLANA_RPC_URL)
  const domainProvider = env(process.env.DOMAIN_PROVIDER).toLowerCase()
  return {
    /** AI companies that receive prompts. Empty when everything is generated by our own templates. */
    ai: [...ai],
    aiText: textKey && textProvider !== "local",
    aiImages: imageOn,
    analytics: /^G-[A-Z0-9]{4,}$/.test(env(process.env.NEXT_PUBLIC_GA_ID)),
    nowPayments: has(process.env.NOWPAYMENTS_API_KEY),
    registrar: domainProvider && domainProvider !== "none" ? env(process.env.NEXT_PUBLIC_REGISTRAR_NAME) || "Dynadot" : "",
    rpc: /helius/i.test(rpc) ? "Helius" : "",
    walletConnect: has(process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID),
  }
}
export type LegalProviders = ReturnType<typeof legalProviders>
